version: '3.8'
services:
  token_crawler:
    build: .
    container_name: token_crawler_once
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./pages:/app/pages
    command: python gmgn_token_info_crawler.py

  kol_scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: kol_scheduler
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - TZ=Asia/Taipei
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "
        python start_scheduler.py > /app/logs/kol_scheduler.log 2>&1
      "